[package]
name = "pinyin-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version= "0.29.0", features = ["event-stream"]}
ratatui = "0.29.0"
tokio = { version = "1.44.2", features = ["full"] }
color-eyre = "0.6.3"
tokio-stream = "0.1.17"
